# -*- coding: utf-8 -*-
MEMBER_NAME = ''
ROOM_ID = 0
MEMBER_ID = 0

# QQ群
AUTO_REPLY_GROUPS = []
MEMBER_ROOM_MSG_GROUPS = []
MEMBER_ROOM_COMMENT_GROUPS = []
MEMBER_WEIBO_GROUPS = []
MEMBER_LIVE_GROUPS = []
MEMBER_ROOM_MSG_LITE_GROUPS = []
JIZI_NOTIFY_GROUPS = []

# 集资
JIZI_KEYWORDS = []
JIZI_LINK = []

WEIBO_KEYWORDS = []
WEIBO_LINK = ''
SUPER_TAG = ''

GONGYAN_KEYWORDS = []
LIVE_LINK = []
LIVE_SCHEDULE = []

MEMBER_ATTR = ''
I_LOVE = []

AT_AUTO_REPLY = []
ROOM_MSG_LITE_NOTIFY = ''

# 公演直播提醒
PERFORMANCE_NOTIFY = ''

# 票务
TICKET_INFO = []

# 微打赏
WDS_ARRAY = []
WDS_PK_ARRAY = []
WDS_NEED_DISPLAY_PK = False
WDS_POSTSCRIPTS = []

# 群内人数监控
GROUP_MEMBER_NUM = {}

# 小白屋room_id列表
ACTIVE_MEMBER_ROOM_ID_LIST = []
# 小黑屋room_id列表
DEACTIVE_MEMBER_ROOM_ID_LIST = []

# 成员member_id列表 直播提醒
LIVING_MEMBER_ID_LIST = []

